### ISSUE TITLE
Refactor hard coded indentation in type declaration template

### ISSUE THREAD

**Issue by saulmaldonado** [saulmaldonado/dotenv-types-generator#1]
Indentation whitespace in the type declaration template is currently hardcoded and based on a 2-space indentation size. 
(3 indentations * 2-space size)

```js
// src/generate.js line 27

  const typeDeclaration = `declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ${mappedTypes.join('      ')}
    }
  }
}
```

Ideally, indentation would need to be calculated dynamically based on the projects style guide specification for indentation size. This information is usually found in a projects `.prettierrc` or `.editorconfig`. One could manually parse these file or install a package to help ex. [https://github.com/editorconfig/editorconfig-core-js](https://github.com/editorconfig/editorconfig-core-js). If there is no specification, default indentation size should be set to 2-space

**Comment by yvz5** [comment]
I don't think that every project "could" have these files for defining indentation.  Would it be better to make an argument defining it ?

**Comment by saulmaldonado** [comment]
Hey @yvz5! I wouldn't be opposed to having a command line option for this and in fact I also think would be the safest idea. It could be an optional option defined like `--indentationSize 4` or `-i 4` with a default fallback value of 2. Then use that argument for defining indentations sizes.

Adding the option would be a great way to get rid of the hard coded value and solve this issue for now.

**Comment by yvz5** [comment]
Hey I came up with an idea to use custom identation for the template file. 
```js
const placeholderText = "types-placeholder";
const template = [
  { "indentation": 0, "value": "declare global {\n" },
  { "indentation": 1, "value": "namespace NodeJS {\n" },
  { "indentation": 2, "value": "interface ProcessEnv {\n" },
  { "indentation": 3, "value":  placeholderText },
  { "indentation": 2, "value": "}\n" },
  { "indentation": 1, "value": "}\n" },
  { "indentation": 0, "value": "}" },
];
```
and a new module that uses this template to create indentation based on a variable:
```js
/**
 * Creates a type definition file template depending on the given indentation size.
 * @param {Number} indentationSize Defines how the template should be indented
 * @param {Array} mappedTypes Mapped type definitions
 */
export const printTypes = (indentationSize, mappedTypes) => {
  let output = "";
  let indentationText = " ".repeat(indentationSize);

  template.forEach(element => {
    const indentation = indentationText.repeat(parseInt(element.indentation));	
	
	if (element.value === placeholderText) {
		mappedTypes.forEach(mappedType => {
			output += `${indentation}${mappedType}\n`;
		});
	}
	else
		output += `${indentation}${element.value}`;			
  });

  return output;
};
```
and in `generate.js`:
```js
const typeDeclaration = printTypes(indentationSize, mappedTypes);

  writeFileSync(`${cwd}/${outPath}env.d.ts`, typeDeclaration);
```

Would this be something that you thought of ? I used empty spaces as using tabs could depend on user settings. Let me know if this is an acceptable approach for you

**Comment by saulmaldonado** [comment]
@yvz5 You have the right idea! I feel like your template array is a good replacement to the template literal I intially had and leaves less room for inconsistencies in formatting. Moving all this to a seperate module would also clean up the `generate.js` file. Just one thing:

The template should be.
```js
const template = [
  { "indentation": 0, "value": "declare global {\n" },
  { "indentation": 1, "value": "namespace NodeJS {\n" },
  { "indentation": 2, "value": "interface ProcessEnv {\n" },
  { "indentation": 3, "value":  placeholderText },
  { "indentation": 2, "value": "}\n" },
  { "indentation": 1, "value": "}\n" },
  { "indentation": 0, "value": "}\n" },
  { "indentation": 0, "value": "\n" },
  { "indentation": 0, "value": "export {};\n" },
];
```

Thanks!
