### ISSUE TITLE
Reads some string vars improperly

### ISSUE THREAD

**Issue by mikestopcontinues** [saulmaldonado/dotenv-types-generator#15]
Hey, awesome lib!

I hit a snag regarding my `NPM_RC` var (required for using github private packages). From this:

```bash
NPM_RC="@secretarcade:registry=https://npm.pkg.github.com/\n//registry.npmjs.org/:_authToken=<SECRET>\n//npm.pkg.github.com/:_authToken=<SECRET>"
```

The above env var string works without incident in other contexts, but I get these three type defs:

```ts
NPM_RC: string;
registry: string;
_authToken: string;
```

You can see how the regex [here](https://github.com/saulmaldonado/dotenv-types-generator/blob/b26a5df99965ac4b70040c750412dd7ef9350ddb/src/generate.js#L21) is interpreting those `=` signs even inside quote marks.

**Comment by saulmaldonado** [comment]
Hey there @mikestopcontinues,

Thanks for bringing this up. I actually ran into the same problem not long ago while working with base64 `.env` variables.

A PR will be merged with a new regex

https://github.com/saulmaldonado/dotenv-types-generator/blob/fix/saulmaldonado-issue15/src/generate.js#L20

The new regex should now only take the first key preceding the first `=` per line regardless of how much leading whitespace (similar to how the dotenv package behaves).

**Comment by mikestopcontinues** [comment]
Much appreciated! Thanks!
