### ISSUE TITLE
Add command line option to make all types optional

### ISSUE THREAD

**Issue by saulmaldonado** [saulmaldonado/dotenv-types-generator#2]
Currently, all types are set to string
```ts
// env.d.ts
  declare global {
  namespace NodeJS {
    interface ProcessEnv {
      API_KEY: string;
      NODE_ENV: string;
    }
  }
}
  
export {};
```
There is the possibility that anyone of these .env values can be end up being undefined at run time. To prevent errors, we can have the option to make all these types optional and have the developer add null/undefined type checkers in their project to ensure their types. This type checking can helpful with debugging in a production or CI environment.

Add a command line flag that makes all ProcessEnv types optional and generates the following a file similar to the following
```ts
// example
  declare global {
  namespace NodeJS {
    interface ProcessEnv {
      API_KEY?: string;
      NODE_ENV?: string;
    }
  }
}
  
export {};
```

For more infomation on nullable types, [https://www.typescriptlang.org/docs/handbook/advanced-types.html#nullable-types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#nullable-types)

**Comment by yvz5** [comment]
hey, I would like to contribute. Is it ok for you to assign me to this issue ?

**Comment by saulmaldonado** [comment]
Thanks this looks great!
