### ISSUE TITLE
Add command line option to add default process.env properties to template

### ISSUE THREAD

**Issue by saulmaldonado** [saulmaldonado/dotenv-types-generator#3]
One of the downsides of generating a custom .d.ts for your .env file is that the default environment variables are excluded from the type declaration.

example from [https://nodejs.org/api/process.html#process_process_env](https://nodejs.org/api/process.html#process_process_env)
```sh
{
  TERM: 'xterm-256color',
  SHELL: '/usr/local/bin/bash',
  USER: 'maciej',
  PATH: '~/.bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin',
  PWD: '/Users/maciej',
  EDITOR: 'vim',
  SHLVL: '1',
  HOME: '/Users/maciej',
  LOGNAME: 'maciej',
  _: '/usr/local/bin/node'
}
```
Other variables such as `NODE_ENV` can be important for specifying configuration between producation, testing and development environments. We can an optional command line option to add default properties back into the declaration file template.
```ts
// example
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      TERM: string;
      SHELL: string;
      USER: string;
      PATH: string;
      PWD: string;
      EDITOR: string;
      SHLVL: string;
      HOME: string;
      LOGNAME: string;
      NODE_ENV: string;
    // ... rest of custom properties
    }
  }
}
  
export {};


```

**Comment by yvz5** [comment]
How should this exactly work ? Get a list of variables from process.env and merge it with a .env file ?

**Comment by saulmaldonado** [comment]
I wish I could have been more specific here. I meant to say something along the lines of **project specific** environment variables that are not specified in the .env file. These are most often environment variables that are automatically configured by libraries e.g. `NODE_ENV`, `BABEL_ENV`, `DEBUG`. Other variables are most likely added by the developer's local machine so unless you have a team working in isolated containers, its not a good idea to merge variables from `process.env` to `.env`.

What I could propose would be to have the option to add these project specific variables through the cli as an array. `dotenv-types-generator --defaults NODE_ENV BABEL_ENV DEBUG`.
[https://github.com/yargs/yargs/blob/master/docs/api.md#arraykey](https://github.com/yargs/yargs/blob/master/docs/api.md#arraykey)

```ts
// example
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: string;
      BABEL_ENV: string;
      DEBUG: string;
    // ... rest of custom properties
    }
  }
}
  
export {};
```

**Comment by yvz5** [comment]
Ah now I understand. This is a great idea. Will implement it soon. I do have a question though:
What if the given parameters collide with the variables inside the .env file ? How do we solve this conflict ? Command line arguments should overwrite the variables from .env IMHO
