### ISSUE TITLE
Add command line option to merge with existing ProcessEnv declaration file.

### ISSUE THREAD

**Issue by saulmaldonado** [saulmaldonado/dotenv-types-generator#4]
Add an option to merge .env types with types from an existing .d.ts file

```ts
// existing file
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      PWD: string;
      EDITOR: string;
      HOME: string;
      NODE_ENV: string;
    }
  }
}
  
export {};
```

.env file
```sh
# .env
API_KEY=123456789
NODE_ENV=production
```

resulting env.d.ts
```ts
// merged .d.ts
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      PWD: string;
      EDITOR: string;
      HOME: string;
      NODE_ENV: string;
      API_KEY: string;
    }
  }
}
  
export {};
```

**Comment by yvz5** [comment]
Hey, I started working on this and stumbled on a regex problem. I am trying to read an existing .d.ts file to subtract the types. I used `/(?<=ProcessEnv\s{)(.+?)(?=})/gs` to list the variables but all I get is one string: 
```
[ '\r\n\t\t\tAPI_KEY?: string;\r\n\t\t\tAPI_KEY2?: string;\r\n\t\t' ]
```
If the merge needs to happen on an existing file, the code needs to somehow filter out the noise. Well the natural way would be to replace unnecessary characters and split the string by `;` to get a list of variable to compare later in the code. But first I wanted to ask you if you know a better regex pattern that would filter out noise and capture each line seperated by `;` ? Or do you think that it would be fine to regex match, replace and split ?

Let me know what you think

**Comment by saulmaldonado** [comment]
@yvz5 You seem to have the right idea going about parsing the file with your first pattern `/(?<=ProcessEnv\s{)(.+?)(?=})/gs`. What I had in mind was using regex match with a similar pattern I used for parsing the .env in `generate.js` 
`/(?<=\s*)\w+\??: string/gim`. This would parse such file 
```ts
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      PWD: string;
      EDITOR: string;
      HOME: string;
      NODE_ENV?: string;
    }
  }
}
  
export {};
```
into `["PWD: string", "EDITOR: string", "HOME: string", "NODE_ENV?: string"]`. Parsing a file using `;` wouldn't work out since a project's linter and formatter could just remove it automatically.

Now my pattern, is not foolproof. It does not first check for a valid env.d.ts and that can lead to an unexpected result. A good way to go about this would be to first test the file with `/(?<=ProcessEnv\s*\{)(.+?)(?=})/gs` and if passed, parse the variables with `/(?<=\s*)\w+\??: string/gim`

Here is a demo of all this in action
[https://codesandbox.io/s/flamboyant-cdn-q5q2j?file=/src/index.js](https://codesandbox.io/s/flamboyant-cdn-q5q2j?file=/src/index.js)

**Comment by yvz5** [comment]
Thanks for your great support! I have another questions: which one of those variables have the priority ? Imagine the following scenario:
- env.d.ts file contains ` V1?: string; V2: string`
- mappedTypes contains `V1,V3`
Now we have a conflict. MappedTypes wants to write V1 variable but it exists in the file with a different signature `?`. What would be the wanted appraoch here ? I would say we base the `d.env.ts` as the source of truth and only add variables that dont exist in the file. What do you think ?

**Comment by saulmaldonado** [comment]
You bring up a great point that I didn't think about at first! I agree with your approach and feel like the default behavior should be for the existing file to take precedent when it comes to type signatures. Perhaps later on we could open up another issue that would add an option to overwrite the default behavior.

**Comment by yvz5** [comment]
Great to hear that we agree on this ! A new PR coming up soon.
